version: '3'
services:
  omlmd-integration-mlmd-server:
    image: gcr.io/tfx-oss-public/ml_metadata_store_server:1.14.0
    container_name: omlmd-integration-mlmd-server
    ports:
      - "9090:8080"
    environment:
      - METADATA_STORE_SERVER_CONFIG_FILE=/tmp/shared/conn_config.pb
    volumes:
      - ./config/ml-metadata:/tmp/shared
  omlmd-integration-model-registry:
    image: docker.io/kubeflow/model-registry:latest
    command: ["proxy", "--hostname", "0.0.0.0", "--mlmd-hostname", "omlmd-integration-mlmd-server", "--mlmd-port", "8080"]
    container_name: omlmd-integration-model-registry
    ports:
      - "8081:8080"
    depends_on:
      - omlmd-integration-mlmd-server
