name: E2E testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e-distribution-registry:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' 
    - name: Install Poetry
      run: |
        pipx install poetry
    - name: Install dependencies
      run: |
        make install
    - name: Start Kind Cluster
      uses: helm/kind-action@v1
      with:
        cluster_name: kind
    - name: Start distribution-registry
      run: |
        ./e2e/deploy_distribution_registry.sh
    - name: Run E2E tests
      run: |
        make test-e2e
    - name: Run E2E tests for CLI # only running once using distribution/registry intentionally
      run: |
        ./e2e/test_cli.sh
  e2e-zot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' 
    - name: Install Poetry
      run: |
        pipx install poetry
    - name: Install dependencies
      run: |
        make install
    - name: Start Kind Cluster
      uses: helm/kind-action@v1
      with:
        cluster_name: kind
    - name: Start Zot
      run: |
        ./e2e/deploy_zot.sh
    - name: Run E2E tests
      run: |
        make test-e2e
  e2e-quay-lite:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' 
    - name: Install Poetry
      run: |
        pipx install poetry
    - name: Install dependencies
      run: |
        make install
    - name: Install ORAS (using it for login) # https://oras.land/docs/installation#linux
      run: |
        VERSION="1.2.0"
        curl -LO "https://github.com/oras-project/oras/releases/download/v${VERSION}/oras_${VERSION}_linux_amd64.tar.gz"
        mkdir -p oras-install/
        tar -zxf oras_${VERSION}_*.tar.gz -C oras-install/
        sudo mv oras-install/oras /usr/local/bin/
        rm -rf oras_${VERSION}_*.tar.gz oras-install/
        oras version
    - name: Start Kind Cluster
      uses: helm/kind-action@v1
      with:
        cluster_name: kind
    - name: Start Quay-lite
      run: |
        ./e2e/deploy_quay_lite.sh
    - name: Run E2E tests
      run: |
        make test-e2e
